"""Generate schema/waterx-config.schema.json (the canonical schema, consumed
by codegen and every parser) AND schema/waterx-config.gate.json (repo-only
strictness ajv checks in CI) from the two live network files. Run from the
repo root:
    python3 scripts/gen_schema.py

Why two outputs: enums for growable vocabularies (source names, methods) live
ONLY in the gate schema. In this repo, schema and data move together, so ajv
can pin the exact vocabulary and catch typos at PR time; a parser generated
from such an enum would instead make every FUTURE vocabulary addition a
breaking change for pinned consumers — the same failure class as the old
closed packages map. Patterns (pubkey, suiId) go in the canonical schema:
patterns biting in parsers is the intended design."""
import json
import sys, os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_schema_lib import SUI_ID, apply_constraints, assert_anchors, build_schema  # noqa: E402

_MVR = {"type": "object", "properties": {
    "name": {"type": "string"}, "package_info_id": dict(SUI_ID), "app_cap_id": dict(SUI_ID),
    "git": {"type": "object", "properties": {"repo": {"type": "string"}, "path": {"type": "string"},
                                             "version": {"type": "integer"}},
            "required": ["repo", "path", "version"], "additionalProperties": False}},
    "required": ["name", "package_info_id", "app_cap_id"], "additionalProperties": False}

TOP = {
    # enum rather than const: quicktype crashes on ANY numeric `const`
    # (typed or not) while a one-value enum generates cleanly and enforces
    # the same pin in ajv and zod (review finding).
    "schema_version": {"type": "integer", "enum": [2],
                       "description": "Format discriminator. This repo serves only version 2 (the consolidated shape); parsers reject anything else."},
    "network": {"enum": ["mainnet", "testnet"]},
    "chain_id": {"type": "string", "minLength": 4},
    # uniform package identity — the ONLY fields allowed per package, and the
    # identity trio is REQUIRED (an identity block missing published_at is a
    # sync bug, not a partial deploy; review finding).
    "packages": {"type": "object", "additionalProperties": {
        "type": "object", "properties": {
            "published_at": dict(SUI_ID), "original_id": dict(SUI_ID),
            "version": {"type": "integer", "minimum": 1},
            "upgrade_capability": dict(SUI_ID), "mvr": _MVR},
        "required": ["published_at", "original_id", "version"],
        "additionalProperties": False}},
    "symbols": {"type": "object", "additionalProperties": {
        "type": "object",
        "properties": {"kind": {"enum": ["perp", "spot", "xstock", "commodity", "fx", "prediction"]}},
        "required": ["kind"], "additionalProperties": False}},
}

# Hand-written constraints overlaid on inferred nodes of the CANONICAL schema
# (parsers inherit these — pattern-class only; see module docstring).
CONSTRAINTS = {
    # Patterns only — prose stays in schema/descriptions.json (the one prose
    # channel; annotate() gives it precedence).
    "oracle_rules/waterx/enclave/pubkey": {"pattern": "^[0-9a-fA-F]{64}$"},
}

# Repo-only strictness: the wire vocabularies, pinned exactly. The canonical
# names are the ones quote-service resolve.rs canonicalizes to (legacy aliases
# it tolerates are deliberately NOT blessed here).
SOURCE_NAMES = [
    "binance_spot", "binance_spot_ws", "binance_usdm_perp_ws",
    "bybit_linear_perp_ws", "gateio_usdt_perp_ws", "bybit_spot_ws",
    "xstock_equity_rest", "okx_spot_ws", "hyperliquid_perp_ws",
    "gateio_spot_ws", "kraken_spot_ws", "pyth_lazer_ws",
]
GATE_CONSTRAINTS = {
    "oracle_rules/waterx/venue_feeds/*/sources/[]/name": {"enum": SOURCE_NAMES},
    "oracle_rules/waterx/venue_feeds/*/method": {"enum": ["direct", "median", "confidence"]},
}


def gate_schema(canonical, constraints):
    """A minimal partial schema holding only the gate constraints, nested to
    mirror the canonical shape (no additionalProperties/required anywhere, so
    it constrains ONLY the listed paths). apply_constraints on the canonical
    schema first proves every path still resolves."""
    root = {"$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "https://config.waterx.app/schema/waterx-config.gate.json",
            "title": "waterx-config repo-only gate",
            "description": "Strictness ajv enforces in THIS repo only (schema and data move together here): exact wire vocabularies that would break pinned parsers if baked into the canonical schema. Generated by scripts/gen_schema.py.",
            "type": "object", "properties": {}}
    for path, extra in constraints.items():
        node = root
        # Each intermediate is typed by the keyword the NEXT hop needs
        # (ajv strict mode wants a type beside every applicator): array
        # before an '[]' hop, object otherwise. Only the listed leaves are
        # constrained — no required/additionalProperties:false anywhere.
        segs = path.split("/")
        for i, seg in enumerate(segs):
            if seg == "*":
                node = node.setdefault("additionalProperties", {})
            elif seg == "[]":
                node = node.setdefault("items", {})
            else:
                node = node.setdefault("properties", {}).setdefault(seg, {})
            if i + 1 < len(segs):
                node.setdefault("type", "array" if segs[i + 1] == "[]" else "object")
        node.clear()
        node.update(extra)
    return root


# Every top-level key must appear here or in schema/optional-fields.json —
# build_schema fails otherwise (coin_registry and evm were silently optional;
# review finding).
REQUIRED_TOP = ["schema_version", "network", "chain_id", "symbols", "packages",
                "objects", "oracle_rules", "coin_registry", "evm"]


def generate(m, t):
    """Build canonical + gate schemas from two instance docs. Importable so
    scripts/test_gen_schema.py exercises the REAL TOP/constraints."""
    schema = build_schema(
        m, t, TOP,
        schema_id="https://config.waterx.app/schema/waterx-config.schema.json",
        title="waterx-config network file",
        description="One WaterX network deployment in the consolidated shape: one symbol universe, uniform package identity, domain-grouped shared objects, and a named per-rule oracle registry. See docs/FIELDS.md.",
        required=REQUIRED_TOP,
    )
    apply_constraints(schema, CONSTRAINTS)
    assert_anchors(schema)
    # Prove the gate paths resolve in the canonical schema (fail-closed).
    apply_constraints(json.loads(json.dumps(schema)), GATE_CONSTRAINTS)
    return schema, gate_schema(schema, GATE_CONSTRAINTS)


if __name__ == "__main__":
    m = json.load(open("mainnet.json"))
    t = json.load(open("testnet.json"))
    schema, gate = generate(m, t)
    json.dump(schema, open("schema/waterx-config.schema.json", "w"), indent=2, ensure_ascii=False)
    json.dump(gate, open("schema/waterx-config.gate.json", "w"), indent=2, ensure_ascii=False)
    print("schema/waterx-config.schema.json + schema/waterx-config.gate.json written")
